services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: ${MONGODB_CONTAINER_NAME:-mongodb}
    hostname: mongodb
    volumes:
      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db/
      - mongodb_log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    networks:
      - backend

  # Mongo-Gui -> User interface for mongo.
  # mongo-gui:
  #   container_name: "mongo-gui"
  #   image: ugleiton/mongo-gui
  #   restart: always
  #   ports:
  #     - "4321:4321"
  #   environment:
  #     - MONGO_URL=mongodb://${MONGODB_EXPRESS_USERNAME}:${MONGODB_EXPRESS_PASSWORD}@mongodb:27017
  #   networks:
  #     - backend
  #   depends_on:
  #     - mongodb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    hostname: mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_CONTAINER_NAME:-mongodb}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_EXPRESS_PASSWORD}
    ports:
      - 8081:8081
    networks:
      - backend
    depends_on:
      - mongodb

volumes:
  mongo_data:
  mongodb_log:

networks:
  backend:
    driver: bridge