services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db/
      - mongodb_log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    networks:
      - backend

  # mongo-gui:
  #   container_name: "mongo-gui"
  #   image: ugleiton/mongo-gui
  #   restart: always
  #   ports:
  #     - "4321:4321"
  #   environment:
  #     - MONGO_URL=mongodb://mongodb:27017
  #   networks:
  #     - backend
  #   depends_on:
  #     - mongodb

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo_express
  #   restart: always
  #   hostname: mongo_express
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_SERVER: 'mongodb' # Tiene que ser igual al nombre del contenedor de mongo
  #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - backend
  #   depends_on:
  #     - mongodb

volumes:
  mongo_data:
  mongodb_log:

networks:
  backend:
    driver: bridge